### ISSUE TITLE
HH:MM:SS doesn't work

### ISSUE THREAD

**Issue by GrayStrider** [klaussinani/signale#103]
I've seen some comments from May 2019 about normalizing timestamps;
I have version 1.4.0 and mine still look like this:
![image](https://user-images.githubusercontent.com/43771776/77248561-77d7ab00-6c8e-11ea-9cf7-8a7e25d4c548.png)
How do I enable 24h display?
Node `v 13.7.0`

**Comment by rudemex** [comment]
Hi @GrayStrider i solved this problem with momentjs to format the day and time and set the time zone.

https://www.npmjs.com/package/signale-logger

**Comment by GrayStrider** [comment]
Low priority, thanks for the tip 👍
