### ISSUE TITLE
nested objects

### ISSUE THREAD

**Issue by GrayStrider** [klaussinani/signale#104]
How to expand `Object` up to certain level?

![image](https://user-images.githubusercontent.com/43771776/77641253-dca54500-6faf-11ea-806a-0dd8664134f1.png)

**Comment by rudemex** [comment]
Hi @GrayStrider , in order to further expand the object, you can use JSON.stringify by adding the replacer and space parameters.

```js
const data = {
    "level1": {
      "level2": {
        "level3": "lorem",
        "level3b":{
          "level4":{
            "level5":"lorem"
          }
        }
      }
    }
  };

logger1.debug(data);
logger1.debug(JSON.stringify(data,null,2));
```

![image](https://user-images.githubusercontent.com/1771743/92058844-fff5cc80-ed65-11ea-9d55-16a664849a63.png)

**Comment by GrayStrider** [comment]
Yeah should've thought of that idk
