### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by Eke** [klaussinani/signale#39]
Are there any plans to support typescript and add `d.ts` file to the project?

**Comment by klauscfhq** [comment]
Yep, ts will be supported very soon, the progress can be tracked on #25

**Comment by Eke** [comment]
@klauscfhq awesome! my bad... did not notice opened PR. Thank you for fast answer.

**Comment by klauscfhq** [comment]
Thank you for taking to suggest it! It is super ok, we can close the issue once the PR is merged and the feature delivered : )

**Comment by resir014** [comment]
Hey everyone,

I didn't see this issue and pull request before @kingdaro and I decided to set up some typings that are currently awaiting PR on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26411). We can compare our progress, and I'd be glad to contribute to PR #25 if needed.

Thanks!

**Comment by chrishelgert** [comment]
Looks like its merged: https://www.npmjs.com/package/@types/signale

**Comment by resir014** [comment]
@chrishelgert Yes, it's merged on DefinitelyTyped, but not here. 😉

**Comment by AnandChowdhary** [comment]
Any plans to publish the package with types? Seems like `./types` exists in `files` but isn't on NPM.

**Comment by NoNameProvided** [comment]
When types are bundled with the project, you don't need to install them separately.

**Comment by AnandChowdhary** [comment]
That's right, but these types aren't published on NPM: https://unpkg.com/browse/signale@1.4.0/

**Comment by lookapanda** [comment]
Can the types please be published on NPM? The types on https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/signale/index.d.ts are incomplete (currently working on a PR)
