### ISSUE TITLE
Add conditional logging

### ISSUE THREAD

**Issue by frontendmonster** [klaussinani/signale#51]
It would be nice to add a property to the custom options that can control logging on a certain condition

### Example
```javascript
const option = {
  stream: process.stdout,
  debug: {
     //...
     condition: process.env.LOG_LEVEL === 'info'
  }
};

proccess.env.LOG_LELEV = 'info';
logger.debug('Some debug info');
> Some debug info

proccess.env.LOG_LEVEL = 'error';
logger.debug('Some debug info');
>
```

**Comment by ivokund** [comment]
This would be really useful, I came looking for just something like that. 

I'd love an option to specify different verbosity levels and run my script with different loggers enabled. For example
```bash
node index.js -v # enables all loggers, except debug/trace
node index.js -vv # enables all loggers
```

In code you could do something like this:
```javascript
// 2 could be the default level. 0 = no logging
logger.setVerbosity(2);
// or set it in options
const option = {
  verbosity: 2
};
// and specify verbosity requirement for each logger to be activated
const option = {
  debug: {
     verbosity: 2,
  }
};
```

**Comment by klauscfhq** [comment]
Yep that is completely needed, the feature will land on the upcoming release : )

**Comment by ericksepulveda** [comment]
+1 to this feature request

**Comment by felixfbecker** [comment]
I can't get this to work to override through `signale.config({ logLevel: ... })`

**Comment by Oxicode** [comment]
> Yep this is definitely needed, the feature will land on the upcoming release : )

Please 🙏
