### ISSUE TITLE
output to devtools console

### ISSUE THREAD

**Issue by selfagency** [klaussinani/signale#58]
**Is your feature request related to a problem? Please describe.**
currently, signale output goes to the CLI but there is no console output if you debug using chrome devtools (i'm using [ndb](https://github.com/GoogleChromeLabs/ndb)).

**Describe the solution you'd like**
i would like for the output to also work in chrome devtools.

**Additional context**
![screenshot 2018-08-09 13 09 06](https://user-images.githubusercontent.com/2541728/43914274-6c360a5c-9bd5-11e8-8972-f4ca7e15e79b.png)

**Comment by rjoydip** [comment]
Right now signale doesn't have browser compatibility. Here are similar issues #14, #47

**Comment by selfagency** [comment]
is it on the roadmap?

**Comment by klaussinani** [comment]
Please follow #14 for updates
