### ISSUE TITLE
Setting the log level

### ISSUE THREAD

**Issue by macmichael01** [klaussinani/signale#72]
**Is your feature request related to a problem? Please describe.**
This is probably more of a question than a feature request. Is there a way to set the log level? Currently its outputting everything to my terminal. 

**Describe the solution you'd like**
Ideally it would be nice to set the log level.

```
new Signale({
  loglevel: 'debug'
});
```

**Comment by ianwalter** [comment]
@macmichael01 Not suggesting this feature shouldn't be added to signale, but I created a log library that can be used with signale and adds this feature (see https://github.com/ianwalter/log#using-a-custom-logger-eg-signale), just FYI.

**Comment by klaussinani** [comment]
The feature will be available soon on the upcoming release. Please follow https://github.com/klaussinani/signale/issues/51 for updates.
