### ISSUE TITLE
`time` and `timeEnd` don't respect underline*: false

### ISSUE THREAD

**Issue by JasonEtco** [klaussinani/signale#77]
**Describe the bug**

Setting `config.underlineLabel` does not remove the underline from the `time` and `timeEnd` methods.

**To Reproduce**

Here's the code I'm working with - I've disabled any of the available `underline*` properties, though `underlineLabel` should be all that's needed:

```js
// index.js
const { Signale } = require('signale')

const logger = new Signale({
  config: {
    underlineLabel: false,
    underlineMessage: false,
    underlinePrefix: false,
    underlineSuffix: false
  }
})

logger.time('A timer')
logger.timeEnd('A timer')
```

```
node index.js
```

![image](https://user-images.githubusercontent.com/10660468/52756902-e26ce080-2fd0-11e9-9c47-b810e426fd3f.png)

**Expected behavior**

I'd expect the `underlineLabel: false` setting to apply to the `time` and `timeEnd` methods like it does for others.

Looks like that's being set here, without a check for `_config.underlineLabel`:

https://github.com/klaussinani/signale/blob/ae5701e610034629b44e028010a18b593e0b64c0/signale.js#L325

**Technical Info (please complete the following information)**
 - OS: MacOS
 - Signale Version: `^1.3.0`
 - Node.js Version: `10.13.0`

**Additional context**

I discovered this in my testing of https://github.com/JasonEtco/actions-toolkit/pull/45 - for some reason, the GitHub Actions log display adds additional spaces for labels with an underline:

![image](https://user-images.githubusercontent.com/10660468/52757035-56a78400-2fd1-11e9-9ce5-04393258e845.png)

I dug into it and discovered this code. I'm sure its needed for regular terminals/output, but it borks a little in Actions so I just disable underlines entirely (since they wouldn't show up anyway):

https://github.com/klaussinani/signale/blob/ae5701e610034629b44e028010a18b593e0b64c0/signale.js#L212-L216

Let me know if I can clarify anything! Happy to open a PR fixing this if y'all are into it.

**Comment by JasonEtco** [comment]
Thanks @klaussinani! ❤️

**Comment by klaussinani** [comment]
Nice catch! Apparently the `stream.Writable` in-use does not support [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code), which combined with the bug/fact that the `time()` & `timeEnd()` unaries did not follow the `underlineLabel` option, resulted in the asymmetrical end-padding of the timer labels. Setting the `underlineLabel` option to `false` should now resolve the issue and display the labels as expected. Also, in the upcoming releases, it is planned for signale to automatically detect if ANSI codes are supported at all, and if not to completely avoide using them. Thank you a lot for taking the time to report the issue! : )
