### ISSUE TITLE
Replace using Date.toLocaleDateString()/Date.toLocaleTimeString() with own implementation

### ISSUE THREAD

**Issue by nielsbril** [klaussinani/signale#84]
**Is your feature request related to a problem? Please describe.**
For the date and timestamp the library uses `Date.toLocaleDateString()` and `Date.toLocaleTimeString()`, which has different output for different Node versions.
For instance, Node `lts/carbon` returns `[2019-3-2] [13:00:00]` and Node `lts/dubnium` returns `[3/2/2019] [1:00:00 PM]`.

**Describe the solution you'd like**
Use an own implementation to format the date and timestamp (preferably `[2019-3-2] [13:00:00]` in my case) , so this is consistent for different Node versions. Possibly add the option to specify the format through the configuration for Signale.

**Comment by klaussinani** [comment]
Nice catch! Thank you for taking the time to file the issue : )

**Comment by klaussinani** [comment]
Fixed on #90 & #91.
Follow-up issue https://github.com/klaussinani/signale/issues/92.
